app:
    build: .
    dockerfile: ./api/Dockerfile
    command: python -u app.py
    ports:
        - "5000:5000"
    volumes:
        - ./api:/app
    links:
        - mongodb

mongodb:
    image: mongo
    container_name: mongodb
    environment:
        - PUID=1000
        - PGID=1000
    volumes:
        - ./mongodb/mongodb/database:/data/db
    ports:
        - 27017:27017
    restart: unless-stopped
